// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlsXT6NyNulqrVGKrBe-ND5ooCb8vkthc',
    appId: '1:983103433432:web:a41670441712580f4c05ad',
    messagingSenderId: '983103433432',
    projectId: 'money-tracker-b1691',
    authDomain: 'money-tracker-b1691.firebaseapp.com',
    storageBucket: 'money-tracker-b1691.appspot.com',
    measurementId: 'G-NP9QWGB20H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsfgYsZnhbojYDNt2y--rvZhpHUbVKok0',
    appId: '1:983103433432:android:aab654cd9d0c58884c05ad',
    messagingSenderId: '983103433432',
    projectId: 'money-tracker-b1691',
    storageBucket: 'money-tracker-b1691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK2a3Yh-vPahpvwtdUevP4Zf08iOF1o_8',
    appId: '1:983103433432:ios:ab12b8e8b0651f994c05ad',
    messagingSenderId: '983103433432',
    projectId: 'money-tracker-b1691',
    storageBucket: 'money-tracker-b1691.appspot.com',
    iosBundleId: 'com.example.diplomMoneyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK2a3Yh-vPahpvwtdUevP4Zf08iOF1o_8',
    appId: '1:983103433432:ios:ab12b8e8b0651f994c05ad',
    messagingSenderId: '983103433432',
    projectId: 'money-tracker-b1691',
    storageBucket: 'money-tracker-b1691.appspot.com',
    iosBundleId: 'com.example.diplomMoneyTracker',
  );
}
